import { Movie } from "./types";

export const data: Movie[] = [
  {
    year: "2014",
    votes: "757074",
    title: "Guardians of the Galaxy",
    runtime: "121",
    revenue: "333.13",
    rating: "8.1",
    rank: "1",
    metascore: "76",
    genre: ["Action", "Adventure", "Sci-Fi"],
    director: "James Gunn",
    description:
      "A group of intergalactic criminals are forced to work together to stop a fanatical warrior from taking control of the universe.",
    actors: ["Chris Pratt", "Vin Diesel", "Bradley Cooper", "Zoe Saldana"],
  },
  {
    year: "2012",
    votes: "485820",
    title: "Prometheus",
    runtime: "124",
    revenue: "126.46",
    rating: "7",
    rank: "2",
    metascore: "65",
    genre: ["Adventure", "Mystery", "Sci-Fi"],
    director: "Ridley Scott",
    description:
      "Following clues to the origin of mankind, a team finds a structure on a distant moon, but they soon realize they are not alone.",
    actors: [
      "Noomi Rapace",
      "Logan Marshall-Green",
      "Michael Fassbender",
      "Charlize Theron",
    ],
  },
  {
    year: "2016",
    votes: "157606",
    title: "Split",
    runtime: "117",
    revenue: "138.12",
    rating: "7.3",
    rank: "3",
    metascore: "62",
    genre: ["Horror", "Thriller"],
    director: "M. Night Shyamalan",
    description:
      "Three girls are kidnapped by a man with a diagnosed 23 distinct personalities. They must try to escape before the apparent emergence of a frightful new 24th.",
    actors: [
      "James McAvoy",
      "Anya Taylor-Joy",
      "Haley Lu Richardson",
      "Jessica Sula",
    ],
  },
  {
    year: "2016",
    votes: "60545",
    title: "Sing",
    runtime: "108",
    revenue: "270.32",
    rating: "7.2",
    rank: "4",
    metascore: "59",
    genre: ["Animation", "Comedy", "Family"],
    director: "Christophe Lourdelet",
    description:
      "In a city of humanoid animals, a hustling theater impresario's attempt to save his theater with a singing competition becomes grander than he anticipates even as its finalists' find that their lives will never be the same.",
    actors: [
      "Matthew McConaughey",
      "Reese Witherspoon",
      "Seth MacFarlane",
      "Scarlett Johansson",
    ],
  },
  {
    year: "2016",
    votes: "393727",
    title: "Suicide Squad",
    runtime: "123",
    revenue: "325.02",
    rating: "6.2",
    rank: "5",
    metascore: "40",
    genre: ["Action", "Adventure", "Fantasy"],
    director: "David Ayer",
    description:
      "A secret government agency recruits some of the most dangerous incarcerated super-villains to form a defensive task force. Their first mission: save the world from the apocalypse.",
    actors: ["Will Smith", "Jared Leto", "Margot Robbie", "Viola Davis"],
  },
  {
    year: "2016",
    votes: "56036",
    title: "The Great Wall",
    runtime: "103",
    revenue: "45.13",
    rating: "6.1",
    rank: "6",
    metascore: "42",
    genre: ["Action", "Adventure", "Fantasy"],
    director: "Yimou Zhang",
    description:
      "European mercenaries searching for black powder become embroiled in the defense of the Great Wall of China against a horde of monstrous creatures.",
    actors: ["Matt Damon", "Tian Jing", "Willem Dafoe", "Andy Lau"],
  },
  {
    year: "2016",
    votes: "258682",
    title: "La La Land",
    runtime: "128",
    revenue: "151.06",
    rating: "8.3",
    rank: "7",
    metascore: "93",
    genre: ["Comedy", "Drama", "Music"],
    director: "Damien Chazelle",
    description: "A jazz pianist falls for an aspiring actress in Los Angeles.",
    actors: ["Ryan Gosling", "Emma Stone", "Rosemarie DeWitt", "J.K. Simmons"],
  },
  {
    year: "2016",
    votes: "2490",
    title: "Mindhorn",
    runtime: "89",
    revenue: "",
    rating: "6.4",
    rank: "8",
    metascore: "71",
    genre: ["Comedy"],
    director: "Sean Foley",
    description:
      'A has-been actor best known for playing the title character in the 1980s detective series "Mindhorn" must work with the police when a serial killer says that he will only speak with Detective Mindhorn, whom he believes to be a real person.',
    actors: [
      "Essie Davis",
      "Andrea Riseborough",
      "Julian Barratt",
      "Kenneth Branagh",
    ],
  },
  {
    year: "2016",
    votes: "7188",
    title: "The Lost City of Z",
    runtime: "141",
    revenue: "8.01",
    rating: "7.1",
    rank: "9",
    metascore: "78",
    genre: ["Action", "Adventure", "Biography"],
    director: "James Gray",
    description:
      "A true-life drama, centering on British explorer Col. Percival Fawcett, who disappeared while searching for a mysterious city in the Amazon in the 1920s.",
    actors: [
      "Charlie Hunnam",
      "Robert Pattinson",
      "Sienna Miller",
      "Tom Holland",
    ],
  },
  {
    year: "2016",
    votes: "192177",
    title: "Passengers",
    runtime: "116",
    revenue: "100.01",
    rating: "7",
    rank: "10",
    metascore: "41",
    genre: ["Adventure", "Drama", "Romance"],
    director: "Morten Tyldum",
    description:
      "A spacecraft traveling to a distant colony planet and transporting thousands of people has a malfunction in its sleep chambers. As a result, two passengers are awakened 90 years early.",
    actors: [
      "Jennifer Lawrence",
      "Chris Pratt",
      "Michael Sheen",
      "Laurence Fishburne",
    ],
  },
  {
    year: "2016",
    votes: "232072",
    title: "Fantastic Beasts and Where to Find Them",
    runtime: "133",
    revenue: "234.02",
    rating: "7.5",
    rank: "11",
    metascore: "66",
    genre: ["Adventure", "Family", "Fantasy"],
    director: "David Yates",
    description:
      "The adventures of writer Newt Scamander in New York's secret community of witches and wizards seventy years before Harry Potter reads his book in school.",
    actors: [
      "Eddie Redmayne",
      "Katherine Waterston",
      "Alison Sudol",
      "Dan Fogler",
    ],
  },
  {
    year: "2016",
    votes: "93103",
    title: "Hidden Figures",
    runtime: "127",
    revenue: "169.27",
    rating: "7.8",
    rank: "12",
    metascore: "74",
    genre: ["Biography", "Drama", "History"],
    director: "Theodore Melfi",
    description:
      "The story of a team of female African-American mathematicians who served a vital role in NASA during the early years of the U.S. space program.",
    actors: [
      "Taraji P. Henson",
      "Octavia Spencer",
      "Janelle Monáe",
      "Kevin Costner",
    ],
  },
  {
    year: "2016",
    votes: "323118",
    title: "Rogue One",
    runtime: "133",
    revenue: "532.17",
    rating: "7.9",
    rank: "13",
    metascore: "65",
    genre: ["Action", "Adventure", "Sci-Fi"],
    director: "Gareth Edwards",
    description:
      "The Rebel Alliance makes a risky move to steal the plans for the Death Star, setting up the epic saga to follow.",
    actors: ["Felicity Jones", "Diego Luna", "Alan Tudyk", "Donnie Yen"],
  },
  {
    year: "2016",
    votes: "118151",
    title: "Moana",
    runtime: "107",
    revenue: "248.75",
    rating: "7.7",
    rank: "14",
    metascore: "81",
    genre: ["Animation", "Adventure", "Comedy"],
    director: "Ron Clements",
    description:
      "In Ancient Polynesia, when a terrible curse incurred by the Demigod Maui reaches an impetuous Chieftain's daughter's island, she answers the Ocean's call to seek out the Demigod to set things right.",
    actors: [
      "Auli'i Cravalho",
      "Dwayne Johnson",
      "Rachel House",
      "Temuera Morrison",
    ],
  },
  {
    year: "2016",
    votes: "8612",
    title: "Colossal",
    runtime: "109",
    revenue: "2.87",
    rating: "6.4",
    rank: "15",
    metascore: "70",
    genre: ["Action", "Comedy", "Drama"],
    director: "Nacho Vigalondo",
    description:
      "Gloria is an out-of-work party girl forced to leave her life in New York City, and move back home. When reports surface that a giant creature is destroying Seoul, she gradually comes to the realization that she is somehow connected to this phenomenon.",
    actors: [
      "Anne Hathaway",
      "Jason Sudeikis",
      "Austin Stowell",
      "Tim Blake Nelson",
    ],
  },
  {
    year: "2016",
    votes: "120259",
    title: "The Secret Life of Pets",
    runtime: "87",
    revenue: "368.31",
    rating: "6.6",
    rank: "16",
    metascore: "61",
    genre: ["Animation", "Adventure", "Comedy"],
    director: "Chris Renaud",
    description:
      "The quiet life of a terrier named Max is upended when his owner takes in Duke, a stray whom Max instantly dislikes.",
    actors: ["Louis C.K.", "Eric Stonestreet", "Kevin Hart", "Lake Bell"],
  },
  {
    year: "2016",
    votes: "211760",
    title: "Hacksaw Ridge",
    runtime: "139",
    revenue: "67.12",
    rating: "8.2",
    rank: "17",
    metascore: "71",
    genre: ["Biography", "Drama", "History"],
    director: "Mel Gibson",
    description:
      "WWII American Army Medic Desmond T. Doss, who served during the Battle of Okinawa, refuses to kill people, and becomes the first man in American history to receive the Medal of Honor without firing a shot.",
    actors: [
      "Andrew Garfield",
      "Sam Worthington",
      "Luke Bracey",
      "Teresa Palmer",
    ],
  },
  {
    year: "2016",
    votes: "150823",
    title: "Jason Bourne",
    runtime: "123",
    revenue: "162.16",
    rating: "6.7",
    rank: "18",
    metascore: "58",
    genre: ["Action", "Thriller"],
    director: "Paul Greengrass",
    description:
      "The CIA's most dangerous former operative is drawn out of hiding to uncover more explosive truths about his past.",
    actors: [
      "Matt Damon",
      "Tommy Lee Jones",
      "Alicia Vikander",
      "Vincent Cassel",
    ],
  },
  {
    year: "2016",
    votes: "102061",
    title: "Lion",
    runtime: "118",
    revenue: "51.69",
    rating: "8.1",
    rank: "19",
    metascore: "69",
    genre: ["Biography", "Drama"],
    director: "Garth Davis",
    description:
      "A five-year-old Indian boy gets lost on the streets of Calcutta, thousands of kilometers from home. He survives many challenges before being adopted by a couple in Australia. 25 years later, he sets out to find his lost family.",
    actors: ["Dev Patel", "Nicole Kidman", "Rooney Mara", "Sunny Pawar"],
  },
  {
    year: "2016",
    votes: "340798",
    title: "Arrival",
    runtime: "116",
    revenue: "100.5",
    rating: "8",
    rank: "20",
    metascore: "81",
    genre: ["Drama", "Mystery", "Sci-Fi"],
    director: "Denis Villeneuve",
    description:
      "When twelve mysterious spacecraft appear around the world, linguistics professor Louise Banks is tasked with interpreting the language of the apparent alien visitors.",
    actors: [
      "Amy Adams",
      "Jeremy Renner",
      "Forest Whitaker",
      "Michael Stuhlbarg",
    ],
  },
  {
    year: "2016",
    votes: "19053",
    title: "Gold",
    runtime: "120",
    revenue: "7.22",
    rating: "6.7",
    rank: "21",
    metascore: "49",
    genre: ["Adventure", "Drama", "Thriller"],
    director: "Stephen Gaghan",
    description:
      "Kenny Wells, a prospector desperate for a lucky break, teams up with a similarly eager geologist and sets off on a journey to find gold in the uncharted jungle of Indonesia.",
    actors: [
      "Matthew McConaughey",
      "Edgar Ramírez",
      "Bryce Dallas Howard",
      "Corey Stoll",
    ],
  },
  {
    year: "2016",
    votes: "134213",
    title: "Manchester by the Sea",
    runtime: "137",
    revenue: "47.7",
    rating: "7.9",
    rank: "22",
    metascore: "96",
    genre: ["Drama"],
    director: "Kenneth Lonergan",
    description:
      "A depressed uncle is asked to take care of his teenage nephew after the boy's father dies.",
    actors: [
      "Casey Affleck",
      "Michelle Williams",
      "Kyle Chandler",
      "Lucas Hedges",
    ],
  },
  {
    year: "2016",
    votes: "1115",
    title: "Hounds of Love",
    runtime: "108",
    revenue: "",
    rating: "6.7",
    rank: "23",
    metascore: "72",
    genre: ["Crime", "Drama", "Horror"],
    director: "Ben Young",
    description:
      "A cold-blooded predatory couple while cruising the streets in search of their next victim, will stumble upon a 17-year-old high school girl, who will be sedated, abducted and chained in the strangers' guest room.",
    actors: [
      "Emma Booth",
      "Ashleigh Cummings",
      "Stephen Curry",
      "Susie Porter",
    ],
  },
  {
    year: "2016",
    votes: "38552",
    title: "Trolls",
    runtime: "92",
    revenue: "153.69",
    rating: "6.5",
    rank: "24",
    metascore: "56",
    genre: ["Animation", "Adventure", "Comedy"],
    director: "Walt Dohrn",
    description:
      "After the Bergens invade Troll Village, Poppy, the happiest Troll ever born, and the curmudgeonly Branch set off on a journey to rescue her friends.",
    actors: [
      "Anna Kendrick",
      "Justin Timberlake",
      "Zooey Deschanel",
      "Christopher Mintz-Plasse",
    ],
  },
  {
    year: "2016",
    votes: "127553",
    title: "Independence Day: Resurgence",
    runtime: "120",
    revenue: "103.14",
    rating: "5.3",
    rank: "25",
    metascore: "32",
    genre: ["Action", "Adventure", "Sci-Fi"],
    director: "Roland Emmerich",
    description:
      "Two decades after the first Independence Day invasion, Earth is faced with a new extra-Solar threat. But will mankind's new space defenses be enough?",
    actors: ["Liam Hemsworth", "Jeff Goldblum", "Bill Pullman", "Maika Monroe"],
  },
  {
    year: "2016",
    votes: "222",
    title: "Paris pieds nus",
    runtime: "83",
    revenue: "",
    rating: "6.8",
    rank: "26",
    metascore: "",
    genre: ["Comedy"],
    director: "Dominique Abel",
    description:
      "Fiona visits Paris for the first time to assist her myopic Aunt Martha. Catastrophes ensue, mainly involving Dom, a homeless man who has yet to have an emotion or thought he was afraid of expressing.",
    actors: [
      "Fiona Gordon",
      "Dominique Abel",
      "Emmanuelle Riva",
      "Pierre Richard",
    ],
  },
  {
    year: "2015",
    votes: "76193",
    title: "Bahubali: The Beginning",
    runtime: "159",
    revenue: "6.5",
    rating: "8.3",
    rank: "27",
    metascore: "",
    genre: ["Action", "Adventure", "Drama"],
    director: "S.S. Rajamouli",
    description:
      "In ancient India, an adventurous and daring man becomes involved in a decades old feud between two warring people.",
    actors: ["Prabhas", "Rana Daggubati", "Anushka Shetty", "Tamannaah Bhatia"],
  },
  {
    year: "2016",
    votes: "523",
    title: "Dead Awake",
    runtime: "99",
    revenue: "0.01",
    rating: "4.7",
    rank: "28",
    metascore: "",
    genre: ["Horror", "Thriller"],
    director: "Phillip Guzman",
    description:
      "A young woman must save herself and her friends from an ancient evil that stalks its victims through the real-life phenomenon of sleep paralysis.",
    actors: [
      "Jocelin Donahue",
      "Jesse Bradford",
      "Jesse Borrego",
      "Lori Petty",
    ],
  },
  {
    year: "2016",
    votes: "66540",
    title: "Bad Moms",
    runtime: "100",
    revenue: "113.08",
    rating: "6.2",
    rank: "29",
    metascore: "60",
    genre: ["Comedy"],
    director: "Jon Lucas",
    description:
      "When three overworked and under-appreciated moms are pushed beyond their limits, they ditch their conventional responsibilities for a jolt of long overdue freedom, fun, and comedic self-indulgence.",
    actors: [
      "Mila Kunis",
      "Kathryn Hahn",
      "Kristen Bell",
      "Christina Applegate",
    ],
  },
  {
    year: "2016",
    votes: "112813",
    title: "Assassin's Creed",
    runtime: "115",
    revenue: "54.65",
    rating: "5.9",
    rank: "30",
    metascore: "36",
    genre: ["Action", "Adventure", "Drama"],
    director: "Justin Kurzel",
    description:
      "When Callum Lynch explores the memories of his ancestor Aguilar and gains the skills of a Master Assassin, he discovers he is a descendant of the secret Assassins society.",
    actors: [
      "Michael Fassbender",
      "Marion Cotillard",
      "Jeremy Irons",
      "Brendan Gleeson",
    ],
  },
  {
    year: "2016",
    votes: "48123",
    title: "Why Him?",
    runtime: "111",
    revenue: "60.31",
    rating: "6.3",
    rank: "31",
    metascore: "39",
    genre: ["Comedy"],
    director: "John Hamburg",
    description:
      "A holiday gathering threatens to go off the rails when Ned Fleming realizes that his daughter's Silicon Valley millionaire boyfriend is about to pop the question.",
    actors: [
      "Zoey Deutch",
      "James Franco",
      "Tangie Ambrose",
      "Cedric the Entertainer",
    ],
  },
  {
    year: "2016",
    votes: "126030",
    title: "Nocturnal Animals",
    runtime: "116",
    revenue: "10.64",
    rating: "7.5",
    rank: "32",
    metascore: "67",
    genre: ["Drama", "Thriller"],
    director: "Tom Ford",
    description:
      "A wealthy art gallery owner is haunted by her ex-husband's novel, a violent thriller she interprets as a symbolic revenge tale.",
    actors: [
      "Amy Adams",
      "Jake Gyllenhaal",
      "Michael Shannon",
      "Aaron Taylor-Johnson",
    ],
  },
  {
    year: "2016",
    votes: "275510",
    title: "X-Men: Apocalypse",
    runtime: "144",
    revenue: "155.33",
    rating: "7.1",
    rank: "33",
    metascore: "52",
    genre: ["Action", "Adventure", "Sci-Fi"],
    director: "Bryan Singer",
    description:
      "After the re-emergence of the world's first mutant, world-destroyer Apocalypse, the X-Men must unite to defeat his extinction level plan.",
    actors: [
      "James McAvoy",
      "Michael Fassbender",
      "Jennifer Lawrence",
      "Nicholas Hoult",
    ],
  },
  {
    year: "2016",
    votes: "627797",
    title: "Deadpool",
    runtime: "108",
    revenue: "363.02",
    rating: "8",
    rank: "34",
    metascore: "65",
    genre: ["Action", "Adventure", "Comedy"],
    director: "Tim Miller",
    description:
      "A fast-talking mercenary with a morbid sense of humor is subjected to a rogue experiment that leaves him with accelerated healing powers and a quest for revenge.",
    actors: ["Ryan Reynolds", "Morena Baccarin", "T.J. Miller", "Ed Skrein"],
  },
  {
    year: "2016",
    votes: "46165",
    title: "Resident Evil: The Final Chapter",
    runtime: "107",
    revenue: "26.84",
    rating: "5.6",
    rank: "35",
    metascore: "49",
    genre: ["Action", "Horror", "Sci-Fi"],
    director: "Paul W.S. Anderson",
    description:
      "Alice returns to where the nightmare began: The Hive in Raccoon City, where the Umbrella Corporation is gathering its forces for a final strike against the only remaining survivors of the apocalypse.",
    actors: ["Milla Jovovich", "Iain Glen", "Ali Larter", "Shawn Roberts"],
  },
  {
    year: "2016",
    votes: "411656",
    title: "Captain America: Civil War",
    runtime: "147",
    revenue: "408.08",
    rating: "7.9",
    rank: "36",
    metascore: "75",
    genre: ["Action", "Adventure", "Sci-Fi"],
    director: "Anthony Russo",
    description:
      "Political interference in the Avengers' activities causes a rift between former allies Captain America and Iron Man.",
    actors: [
      "Chris Evans",
      "Robert Downey Jr.",
      "Scarlett Johansson",
      "Sebastian Stan",
    ],
  },
  {
    year: "2014",
    votes: "1047747",
    title: "Interstellar",
    runtime: "169",
    revenue: "187.99",
    rating: "8.6",
    rank: "37",
    metascore: "74",
    genre: ["Adventure", "Drama", "Sci-Fi"],
    director: "Christopher Nolan",
    description:
      "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    actors: [
      "Matthew McConaughey",
      "Anne Hathaway",
      "Jessica Chastain",
      "Mackenzie Foy",
    ],
  },
  {
    year: "2016",
    votes: "293732",
    title: "Doctor Strange",
    runtime: "115",
    revenue: "232.6",
    rating: "7.6",
    rank: "38",
    metascore: "72",
    genre: ["Action", "Adventure", "Fantasy"],
    director: "Scott Derrickson",
    description:
      "While on a journey of physical and spiritual healing, a brilliant neurosurgeon is drawn into the world of the mystic arts.",
    actors: [
      "Benedict Cumberbatch",
      "Chiwetel Ejiofor",
      "Rachel McAdams",
      "Benedict Wong",
    ],
  },
  {
    year: "2016",
    votes: "122853",
    title: "The Magnificent Seven",
    runtime: "132",
    revenue: "93.38",
    rating: "6.9",
    rank: "39",
    metascore: "54",
    genre: ["Action", "Adventure", "Western"],
    director: "Antoine Fuqua",
    description:
      "Seven gunmen in the old west gradually come together to help a poor village against savage thieves.",
    actors: [
      "Denzel Washington",
      "Chris Pratt",
      "Ethan Hawke",
      "Vincent D'Onofrio",
    ],
  },
  {
    year: "2007",
    votes: "241",
    title: "5- 25- 77",
    runtime: "113",
    revenue: "",
    rating: "7.1",
    rank: "40",
    metascore: "",
    genre: ["Comedy", "Drama"],
    director: "Patrick Read Johnson",
    description:
      "Alienated, hopeful-filmmaker Pat Johnson's epic story growing up in rural Illinois, falling in love, and becoming the first fan of the movie that changed everything.",
    actors: [
      "John Francis Daley",
      "Austin Pendleton",
      "Colleen Camp",
      "Neil Flynn",
    ],
  },
  {
    year: "2016",
    votes: "120690",
    title: "Sausage Party",
    runtime: "89",
    revenue: "97.66",
    rating: "6.3",
    rank: "41",
    metascore: "66",
    genre: ["Animation", "Adventure", "Comedy"],
    director: "Greg Tiernan",
    description: "A sausage strives to discover the truth about his existence.",
    actors: ["Seth Rogen", "Kristen Wiig", "Jonah Hill", "Alistair Abell"],
  },
  {
    year: "2016",
    votes: "135095",
    title: "Moonlight",
    runtime: "111",
    revenue: "27.85",
    rating: "7.5",
    rank: "42",
    metascore: "99",
    genre: ["Drama"],
    director: "Barry Jenkins",
    description:
      "A chronicle of the childhood, adolescence and burgeoning adulthood of a young, African-American, gay man growing up in a rough neighborhood of Miami.",
    actors: [
      "Mahershala Ali",
      "Shariff Earp",
      "Duan Sanderson",
      "Alex R. Hibbert",
    ],
  },
  {
    year: "2016",
    votes: "496",
    title: "Don't Fuck in the Woods",
    runtime: "73",
    revenue: "",
    rating: "2.7",
    rank: "43",
    metascore: "",
    genre: ["Horror"],
    director: "Shawn Burkett",
    description:
      "A group of friends are going on a camping trip to celebrate graduating college. But once they enter the woods, the proverbial shit starts to hit the fan.",
    actors: ["Brittany Blanton", "Ayse Howard", "Roman Jossart", "Nadia White"],
  },
  {
    year: "2016",
    votes: "37033",
    title: "The Founder",
    runtime: "115",
    revenue: "12.79",
    rating: "7.2",
    rank: "44",
    metascore: "66",
    genre: ["Biography", "Drama", "History"],
    director: "John Lee Hancock",
    description:
      "The story of Ray Kroc, a salesman who turned two brothers' innovative fast food eatery, McDonald's, into one of the biggest restaurant businesses in the world with a combination of ambition, persistence, and ruthlessness.",
    actors: [
      "Michael Keaton",
      "Nick Offerman",
      "John Carroll Lynch",
      "Linda Cardellini",
    ],
  },
  {
    year: "2016",
    votes: "279",
    title: "Lowriders",
    runtime: "99",
    revenue: "4.21",
    rating: "6.3",
    rank: "45",
    metascore: "57",
    genre: ["Drama"],
    director: "Ricardo de Montreuil",
    description:
      "A young street artist in East Los Angeles is caught between his father's obsession with lowrider car culture, his ex-felon brother and his need for self-expression.",
    actors: [
      "Gabriel Chavarria",
      "Demián Bichir",
      "Theo Rossi",
      "Tony Revolori",
    ],
  },
];
